(package "js-comint"
         "1.2.0"
         "JavaScript interpreter in window.")

(website-url "https://github.com/redguardtoo/js-comint")
(keywords "javascript" "node" "inferior-mode" "convenience")

(package-file "js-comint.el")

(script "test" "eask test ert test/*tests.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")

(development
 (depends-on "el-mock")
 (depends-on "nvm")
 (depends-on "company")
 (depends-on "ert-async"))
